Repository Project-OSmOSE/OSEkit, pull requests merged in 2024-07, with the labels that each got.

#166 update mpl and black
  pyproject.toml
Labels: bug

#165 164 accept flac files
  advanced_use_cases/Soundscape/1_generate_LTAS.py
  advanced_use_cases/Soundscape/2_generate_EPD.py
  advanced_use_cases/Weather/windspeed_estimation.py
  basic_use_cases/Auxiliary/joiner_auxiliary.py
  basic_use_cases/Dataset/1_build_dataset.py
  basic_use_cases/Dataset/4_dealwith_anomalies.py
  docs/conf.py
  docs/gallery_advanced_use_cases/Soundscape/1_generate_LTAS.ipynb
  docs/gallery_advanced_use_cases/Soundscape/1_generate_LTAS.py
  docs/gallery_advanced_use_cases/Soundscape/2_generate_EPD.ipynb
  docs/gallery_advanced_use_cases/Soundscape/2_generate_EPD.py
  docs/gallery_advanced_use_cases/Soundscape/compute_LTAS.ipynb
  docs/gallery_advanced_use_cases/Soundscape/compute_LTAS.py
  docs/gallery_advanced_use_cases/Weather/windspeed_estimation.ipynb
  docs/gallery_advanced_use_cases/Weather/windspeed_estimation.py
  docs/gallery_basic_use_cases/Auxiliary/joiner_auxiliary.ipynb
  docs/gallery_basic_use_cases/Auxiliary/joiner_auxiliary.py
  docs/gallery_basic_use_cases/Dataset/1_build_dataset.ipynb
  docs/gallery_basic_use_cases/Dataset/1_build_dataset.py
  docs/gallery_basic_use_cases/Dataset/2_mobile_hydrophone.ipynb
  docs/gallery_basic_use_cases/Dataset/3_segment_resample_dataset.ipynb
  docs/gallery_basic_use_cases/Dataset/4_dealwith_anomalies.ipynb
  docs/gallery_basic_use_cases/Dataset/4_dealwith_anomalies.py
  docs/gallery_basic_use_cases/Dataset/4_explore_metadata.ipynb
  docs/gallery_basic_use_cases/Dataset/5_explore_metadata.ipynb
  docs/gallery_basic_use_cases/Spectrogram/1_generate_spectrogram.ipynb
  docs/gallery_basic_use_cases/Spectrogram/2_tune_parameters.ipynb
  src/OSmOSE/Auxiliary.py
  src/OSmOSE/Dataset.py
  src/OSmOSE/Spectrogram.py
  src/OSmOSE/Weather.py
  src/OSmOSE/__init__.py
  src/OSmOSE/cluster/audio_reshaper.py
  src/OSmOSE/cluster/merge_timestamp_csv.py
  src/OSmOSE/cluster/resample.py
  src/OSmOSE/cluster/reshaper.sh
  src/OSmOSE/config.py
  src/OSmOSE/frequency_scales/frequency_scale_serializer.py
  src/OSmOSE/func_api.py
  src/OSmOSE/jointure.py
  src/OSmOSE/timestamps.py
  src/OSmOSE/utils/core_utils.py
  src/OSmOSE/utils/timestamp_utils.py
  tests/conftest.py
  tests/test_dataset.py
  tests/test_spectrogram.py
Labels: data format

#174 Pc add verbose attribute in spectrogram
  src/OSmOSE/Spectrogram.py
Labels: short term

#175 164 accept flac files
  poetry.lock
  src/OSmOSE/Dataset.py
  src/OSmOSE/Spectrogram.py
  src/OSmOSE/cluster/audio_reshaper.py
  src/OSmOSE/cluster/resample.py
  src/OSmOSE/timestamps.py
  src/OSmOSE/utils/audio_utils.py
  src/OSmOSE/utils/core_utils.py
  tests/conftest.py
  tests/test_spectrogram.py
Labels: data format

#183 update on_datarmor page
  docs/_static/extranet_connexion.pdf
  docs/figures/FTP_transfer.png
  docs/figures/SSHconnexion.png
  docs/figures/jupyterhub.png
  docs/figures/jupyterhub_ressource.png
  docs/on_datarmor.rst
Labels: documentation

#188 184 generate spectrograms with wav shorter than desired duration
  src/OSmOSE/Spectrogram.py
  src/OSmOSE/cluster/audio_reshaper.py
Labels: bug, data format
