Repository Project-OSmOSE/OSEkit, pull requests merged in 2025-03, with the labels that each got.

#250 useless utils
  src/OSmOSE/utils/postprocess_utils.py
Labels: data format

#251 Feature/timezone management
  src/OSmOSE/core_api/audio_dataset.py
  src/OSmOSE/core_api/audio_file.py
  src/OSmOSE/core_api/base_dataset.py
  src/OSmOSE/core_api/base_file.py
  src/OSmOSE/core_api/spectro_dataset.py
  src/OSmOSE/core_api/spectro_file.py
  src/OSmOSE/utils/timestamp_utils.py
  tests/test_audio.py
  tests/test_files.py
  tests/test_timestamp_utils.py
Labels: short term

#257 [Optimization] Event overlap
  src/OSmOSE/core_api/event.py
  tests/test_event.py
Labels: high priority, short term

#258 Feature/strptime format list
  src/OSmOSE/utils/timestamp_utils.py
  tests/test_timestamp_utils.py
Labels: short term
